monorepo_root = true
[monorepo]
config_roots = [
    "apps/api",
    "apps/web",
    "apps/home",
    "apps/android",
    "apps/desktop"
]

[settings]
env_file = ".env"

[hooks.enter]
script = """
    echo 'Project IronBook'
"""

[shell_alias]
root = "cd {{config_root}}"
android = "cd {{config_root}}/apps/android"
api = "cd {{config_root}}/apps/api"
desktop = "cd {{config_root}}/apps/desktop"
home = "cd {{config_root}}/apps/home"
web = "cd {{config_root}}/apps/web"
ironbook = "{{config_root}}/scripts/ironbook.sh"

[tasks."setup"]
description = "Install all dependencies"
run = [
  "mise //apps/home:setup",
  "mise //apps/api:setup",
  "mise //apps/web:setup",
  "mise //apps/android:setup",
  "mise //apps/desktop:setup",
]

[tools]
pre-commit = "4.6.2"
protobuf = "35.1"
