syntax = "proto3";

package system;

service SystemService {
  rpc Greet(GreetRequest) returns (GreetResponse);
  rpc HealthReport(HealthReportRequest) returns (HealthReportResponse);
  rpc GenerateApiKey(ApiKeyRequest) returns (ApiKeyResponse);
}

message GreetRequest {}

message GreetResponse {
  string message = 1;
  string status = 2;
}

message HealthReportRequest {}

message HealthReportResponse {
  string overall = 1;
}

message ApiKeyRequest {
  string name = 1;
  string owner_email = 2;
  optional string api_key = 3;
}

message ApiKeyResponse {
  string token = 1;
}
