services:
  ironbook_db:
    image: postgres:17
    container_name: ironbook_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ironbook
    volumes:
      - pg_data:/var/lib/postgresql/data
  ironbook_home:
    build:
      context: .
      dockerfile: ../../../apps/home/Dockerfile
    container_name: ironbook_home
    ports:
      - "${HOST_PORT}:3000"
    environment:
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      HOST_PORT: ${HOST_PORT}
    restart: unless-stopped

volumes:
  pg_data:
