[package]
name = "ironbook_api"
version = "0.1.2-alpha"
edition = "2024"

[dependencies]
# Web framework
axum = { version = "0.8", features = ["macros"] }
tower-http = { version = "0.6", features = ["cors"] }

# gRPC dependencies
tonic = "0.14"
tonic-reflection = "0.14"
prost = "0.14"
tonic-prost = "0.14"

# Async and Runtime
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }

# Database
sqlx = { version = "0.8", features = [
  "runtime-tokio-rustls",
  "postgres",
  "macros",
  "migrate",
  "chrono"
] }

# Environment and Data Utilities
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
anyhow = "1.0.103"
thiserror = "2.0"
serde_json = "1.0.150"
rand = "0.10.2"
chrono = "0.4.45"
argon2 = { version = "0.5.3", features = ["password-hash"]}
sha2 = "0.11.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"]}
tracing-appender = "0.2.5"
hmac = "0.13.0"
hex = "0.4.3"

[build-dependencies]
# Required to compile protobuf files to Rust files
tonic-prost-build = "0.14"

[features]
integration-tests = []

[profile.release]
opt-level = 3
lto = true
strip = true
panic = "abort"
