[tools]
rust = { version = "1.95.0", components = ["rustfmt", "clippy"], targets = ["x86_64-pc-windows-gnu"] }
"cargo:cargo-watch" = "8.5.3"
"cargo:sqlx-cli" = { version = "0.9.0", features = ["postgres", "rustls"] }

[tasks."setup"]
description = "Setup API"
depends = "db:migrate"
run = "cargo check"

[tasks."dev"]
description = "Run Rust API Dev Server"
depends = "db:up"
run = "trap 'exit 0' INT TERM; cargo watch -c -w src -w Cargo.toml -i '*.md' -i 'logs/*' -i 'target/*' -x 'run --bin ironbook_api'"

[tasks."test"]
description = "Run Tests for Rust API"
run = "cargo test"

[tasks."test-full"]
description = "Run Tests, including Database related for Rust API"
depends = "db:migrate"
run = "mise exec -- cargo test --features integration-tests"

[tasks."db:up"]
description = "Starts the ironbook_db service from dev.yaml"
dir = "../../infra/docker/compose"
run = "docker compose -f dev.yaml up ironbook_db -d"

[tasks."db:down"]
description = "Stops the ironbook_db service from dev.yaml"
dir = "../../infra/docker/compose"
run = "docker compose -f dev.yaml down ironbook_db"

[tasks."db:restart"]
description = "Restarts the ironbook_db service from dev.yaml"
run = [
    "mise run db:down",
    "mise run db:up",
]

[tasks."db:migrate"]
description = "Apply pending database migrations"
run = [
    "mise run db:up",
    "mise exec -- cargo sqlx migrate run",
]

[tasks."db:prepare"]
description = "Prepares the .sqlx files for offline development"
depends = "db:up"
run = "mise exec -- cargo sqlx prepare"

[tasks."db:reset"]
description = "Reset database and apply migrations"
depends = "db:restart"
run = "mise exec -- cargo sqlx database reset"
