name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-commit:
    name: Run Pre-Commit Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up mise environment
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Run project setup script
        run: |
          scripts/ironbook.sh setup

      - name: Run pre-commit checks
        run: mise exec -- pre-commit run --hook-stage pre-push --all-files
