name: Build & Publish All Releases

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- SETUP ENVIRONMENT ---
      - name: Set up mise environment
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Run project setup script
        run: |
          scripts/ironbook.sh setup

      # --- IMPORT SECRETS ---
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY }}
        run: |
          echo -n "$ENCODED_STRING" | base64 --decode > apps/android/ironbook.keystore

      # --- BUILD ---
      - name: Build Release
        env:
          RELEASE_GPG_KEY: ${{ steps.import_gpg.outputs.fingerprint }}
          KEYSTORE_PATH: "ironbook.keystore"
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          scripts/ironbook.sh build "${GITHUB_REF_NAME#v}"

      # --- PUBLISH ---
      - name: Upload All Release Assets
        uses: softprops/action-gh-release@v3
        with:
          working_directory: output
          files: |
            android/*.zip
            android/*.zip.asc
            api/linux/*.zip
            api/linux/*.zip.asc
            api/windows/*.zip
            api/windows/*.zip.asc
            desktop/linux/*.zip
            desktop/linux/*.zip.asc
            desktop/windows/*.zip
            desktop/windows/*.zip.asc
            home/*.zip
            home/*.zip.asc
            installer/*.zip
            installer/*.zip.asc
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          body_path: output/"${GITHUB_REF_NAME#v}"*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
